id: alien4cloud-Janus-plugin
name: Janus PaaS provider
version: ${project.version}
description: >
  Plugin that contains a single paas provider for deployments on Hpc env.
configuration_class: alien4cloud.plugin.Janus.JanusPluginConfiguration
component_descriptors:
  - bean_name: Janus-orchestrator-factory
    name: Janus Orchestrator Factory
    description: >
      Alien Plugin for Janus
