tosca_definitions_version: alien_dsl_1_4_0

template_name: janus-kubernetes-types
template_author: Janus
template_version: ${janus.types.version}

imports:
  - janus-docker-types:${janus.types.version}


artifact_types:
  tosca.artifacts.Deployment.Image.Container.Docker.Kubernetes:
    description: Docker Container Image to be deployed by Kubernetes
    derived_from: tosca.artifacts.Deployment.Image.Container.Docker

node_types:
  janus.nodes.KubernetesVolume:
    derived_from: janus.nodes.DockerVolume
    properties:
      name:
        type: string
        required: true
        description: >
          The volume name
    capabilities:
      mount:
        type: janus.capabilities.KubernetesVolume

  janus.nodes.KubernetesVolume.EmptyDir:
    derived_from: janus.nodes.KubernetesVolume
    properties:
      volume_type:
        type: string
        required: true
        description: >
          Specifies the volume type. Must be one of the supported kubernetes volume types.
          For ex, emptyDir, hostPath, secret, etc.
        default: emptyDir
      medium:
        type: string
        description: >
          What type of storage medium should back this directory. The default is "" which means to use the node's default medium.
          Must be an empty string (default) or Memory.
        required: false

capability_types:
  janus.capabilities.KubernetesVolume:
    derived_from: janus.capabilities.DockerVolume
    description: >
      Capability to mount a Kubernetes volume
    properties:
      read_only:
        type: boolean
        required: false
        description: Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false.
      sub_path:
        type: string
        required: false
        description:  Path within the volume from which the container's volume should be mounted. Defaults to "" (volume's root).